[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 80, lines = 42 }
padding = { x = 10, y = 10 }
decorations = "Buttonless"
option_as_alt = "Both"

[scrolling]
history = 100000

[font]
normal = { family = "0xProto", style = "Regular" }
#size   = 18                     # for retina

[colors.primary]
background = "#21084a"
foreground = "#fffbf6"

[colors.cursor]
text = "#ffffff"
cursor = "#ff291d"

[colors.normal]
black = "#000000"
red = "#ff2603"
green = "#9be205"
yellow = "#ffc400"
blue = "#00a2fa"
magenta = "#815bb5"
cyan = "#00deef"
white = "#ffffff"

[colors.bright]
black = "#565656"
red = "#ff4250"
green = "#b8e36e"
yellow = "#ffd852"
blue = "#00a6ff"
magenta = "#ac7bf0"
cyan = "#74fdf3"
white = "#ffffff"

[colors.dim]
black = "#565656"
red = "#ff4250"
green = "#b8e36e"
yellow = "#ffd852"
blue = "#00a6ff"
magenta = "#ac7bf0"
cyan = "#74fdf3"
white = "#ffffff"

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Beam", blinking = "Never" }

[mouse]
#hide_when_typing = true

[hints]
enabled = [
  # { <regex>, <hyperlinks>, <post_processing>, <persist>, <action>, <command>, <binding>, <mouse> }
  #{ hyperlinks = true, post_processing = true, persist = true, command = "open", binding = { key = "o", mods = "control|shift" }, mouse.enabled = false },
  { regex = "https?://[^ ]*", post_processing = true, persist = true, command = "open", binding = { key = "o", mods = "control|shift" }, mouse.enabled = false },
  { regex = "[a-z0-9]{40}", action = "Copy", binding = { key = "h", mods = "control|shift" }, mouse.enabled = false }
]

[keyboard]
bindings = [
  # { <key>, <mods>, <mode>, <command> | <chars> | <action> }
  { key = "T",      mods = "command", action = "CreateNewWindow" },
  { key = "T",      mods = "control", action = "CreateNewWindow" },
  { key = "Return", mods = "command", action = "CreateNewWindow" },
]
